# Neden NumPy?

In [10]:
a = [1,2,3,4]
b = [2,3,4,5]

In [11]:
ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [12]:
import numpy as np

In [13]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [14]:
a * b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [12]:
import numpy as np

In [13]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [14]:
a = np.array([1,2,3,4,5])

In [15]:
type(a)

numpy.ndarray

In [16]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [ ]:
#SIFIRDAN ARRAY OLUŞTURMA

In [17]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [13]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [14]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
np.random.normal(10, 4, (3,4))

array([[ 7.95311755, 18.88626347,  6.68342754,  9.41779354],
       [ 6.56580837,  9.3286982 ,  2.81822871, 11.70010496],
       [15.3764241 ,  8.20890978,  8.67603323,  5.88175198]])

In [16]:
np.random.randint(0,10, (3,3))

array([[9, 0, 2],
       [1, 1, 2],
       [5, 7, 8]])

# Numpy Özellikleri

* **ndim**: _boyut sayısı_
* **shape**: _boyut bilgisi_
* **size**: _toplam eleman sayısı_
* **dtype**: _array veri tipi_

In [26]:
import numpy as np

In [27]:
np.random.randint(10, size = 10)

array([8, 6, 6, 2, 6, 6, 1, 1, 9, 4])

In [28]:
a = np.random.randint(10, size = 10)

In [29]:
a.ndim

1

In [30]:
a.shape

(10,)

In [31]:
a.size

10

In [32]:
a.dtype

dtype('int32')

In [33]:
b = np.random.randint(10, size = (3,5))

In [34]:
b

array([[4, 9, 3, 4, 3],
       [3, 6, 0, 1, 5],
       [1, 4, 4, 0, 6]])

In [22]:
b.ndim

2

In [23]:
b.shape

(3, 5)

In [24]:
b.size

15

In [25]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (Reshaping)

In [1]:
import numpy as np

In [44]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a = np.arange(1,10)

In [47]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a.ndim

1

In [49]:
b = a.reshape((1,9))

In [50]:
b.ndim

2

# Array Birlestirme (Concatenation)

In [51]:
import numpy as np

In [52]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [53]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [54]:
z = np.array([7,8,9])

In [55]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
#iki boyut

In [57]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [58]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [60]:
import numpy as np

In [61]:
x = np.array([1,2,3,99,99,3,2,1])

In [62]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [63]:
a,b,c = np.split(x, [3,5])

In [64]:
a

array([1, 2, 3])

In [65]:
b

array([99, 99])

In [66]:
c

array([3, 2, 1])

In [67]:
#iki boyutlu ayırma

In [68]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [70]:
ust, alt = np.vsplit(m, [2])

In [71]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [75]:
sag, sol = np.hsplit(m, [2])

In [76]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [77]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [ ]:
np.sort(v)

In [5]:
v

array([2, 1, 4, 3, 5])

In [6]:
v.sort()

In [7]:
v

array([1, 2, 3, 4, 5])

In [ ]:
#iki boyutlu array siralama

In [10]:
m = np.random.normal(20,5, (3,3))

In [11]:
m

array([[25.45684489, 21.83575476, 26.06913773],
       [17.50480621, 18.65456644, 25.99114299],
       [15.28755765, 21.08674903, 16.10947821]])

In [12]:
np.sort(m, axis = 1)

array([[21.83575476, 25.45684489, 26.06913773],
       [17.50480621, 18.65456644, 25.99114299],
       [15.28755765, 16.10947821, 21.08674903]])

In [13]:
np.sort(m, axis = 0)

array([[15.28755765, 18.65456644, 16.10947821],
       [17.50480621, 21.08674903, 25.99114299],
       [25.45684489, 21.83575476, 26.06913773]])

# Index ile Elemanlara Erişmek

In [78]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([8, 8, 6, 1, 6, 8, 1, 6, 1, 0])

In [79]:
a[0]

8

In [80]:
a[-1]

0

In [81]:
a[0] = 100

In [82]:
a

array([100,   8,   6,   1,   6,   8,   1,   6,   1,   0])

In [83]:
m = np.random.randint(10, size = (3,5))
m

array([[5, 1, 2, 9, 5],
       [0, 6, 4, 1, 5],
       [7, 3, 6, 8, 3]])

In [84]:
m[0,0]

5

In [85]:
m[1,1]

6

In [86]:
m[1, 4]

5

In [87]:
m[1, 4] = 99

In [88]:
m

array([[ 5,  1,  2,  9,  5],
       [ 0,  6,  4,  1, 99],
       [ 7,  3,  6,  8,  3]])

In [89]:
m[1,4] = 2.2

In [90]:
m

array([[5, 1, 2, 9, 5],
       [0, 6, 4, 1, 2],
       [7, 3, 6, 8, 3]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [91]:
import numpy as np

In [92]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [93]:
a[0:3]

array([20, 21, 22])

In [94]:
a[:3]

array([20, 21, 22])

In [95]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [96]:
a[1::2]

array([21, 23, 25, 27, 29])

In [97]:
a[0::2]

array([20, 22, 24, 26, 28])

In [98]:
a[2::2]

array([22, 24, 26, 28])

In [99]:
a[0::3]

array([20, 23, 26, 29])

In [100]:
#iki boyutlu slice islemleri

In [101]:
m = np.random.randint(10, size = (5,5))

In [102]:
m

array([[0, 6, 9, 3, 9],
       [3, 9, 8, 9, 1],
       [2, 7, 5, 8, 2],
       [2, 4, 4, 8, 7],
       [0, 3, 7, 0, 7]])

In [103]:
m[:,0]

array([0, 3, 2, 2, 0])

In [104]:
m[:,1]

array([6, 9, 7, 4, 3])

In [105]:
m[:,4]

array([9, 1, 2, 7, 7])

In [106]:
m

array([[0, 6, 9, 3, 9],
       [3, 9, 8, 9, 1],
       [2, 7, 5, 8, 2],
       [2, 4, 4, 8, 7],
       [0, 3, 7, 0, 7]])

In [107]:
m[0,:]

array([0, 6, 9, 3, 9])

In [108]:
m[0]

array([0, 6, 9, 3, 9])

In [109]:
m[1,:]

array([3, 9, 8, 9, 1])

In [110]:
m[0:2, 0:3]

array([[0, 6, 9],
       [3, 9, 8]])

In [111]:
m[:,0:2]

array([[0, 6],
       [3, 9],
       [2, 7],
       [2, 4],
       [0, 3]])

In [112]:
m

array([[0, 6, 9, 3, 9],
       [3, 9, 8, 9, 1],
       [2, 7, 5, 8, 2],
       [2, 4, 4, 8, 7],
       [0, 3, 7, 0, 7]])

In [113]:
m[1:3, 0:2]

array([[3, 9],
       [2, 7]])

# Alt Küme Üzerinde İşlem Yapmak

In [116]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[1, 6, 9, 3, 9],
       [6, 1, 2, 9, 7],
       [7, 3, 9, 8, 1],
       [9, 9, 0, 4, 5],
       [9, 3, 5, 1, 6]])

In [117]:
alt_a = a[0:3, 0:2]
alt_a

array([[1, 6],
       [6, 1],
       [7, 3]])

In [118]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [119]:
alt_a

array([[99999,     6],
       [    6,   888],
       [    7,     3]])

In [120]:
a

array([[99999,     6,     9,     3,     9],
       [    6,   888,     2,     9,     7],
       [    7,     3,     9,     8,     1],
       [    9,     9,     0,     4,     5],
       [    9,     3,     5,     1,     6]])

In [121]:
m = np.random.randint(10, size = (5, 5))
m

array([[1, 6, 3, 9, 9],
       [9, 7, 7, 8, 8],
       [8, 8, 2, 6, 6],
       [9, 9, 3, 7, 7],
       [7, 7, 4, 8, 4]])

In [122]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[1, 6],
       [9, 7],
       [8, 8]])

In [123]:
alt_b[0,0] = 9999

In [124]:
alt_b

array([[9999,    6],
       [   9,    7],
       [   8,    8]])

In [11]:
m

array([[0, 5, 2, 6, 8],
       [1, 7, 8, 7, 7],
       [3, 2, 1, 1, 9],
       [5, 0, 9, 2, 8],
       [4, 4, 6, 0, 7]])

# Fancy Index ile Elemanlara Erişmek

In [125]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [126]:
v[1]

3

In [127]:
v[3]

9

In [128]:
v[5]

15

In [129]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [130]:
al_getir = [1,3,5]

In [131]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [132]:
v[al_getir]

array([ 3,  9, 15])

In [133]:
#iki boyutta fancy

In [134]:
m = np.arange(9).reshape((3,3))

In [135]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [136]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [137]:
m[satir, sutun]

array([1, 5])

In [138]:
#basit index ile fancy index

In [139]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [140]:
m[0, [1,2]]

array([1, 2])

In [141]:
#slice ile fancy

In [150]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [151]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [152]:
v < 3

array([ True,  True, False, False, False])

In [153]:
v[v < 3]

array([1, 2])

In [154]:
v[v > 3]

array([4, 5])

In [155]:
v[v >= 3]

array([3, 4, 5])

In [156]:
v[v <= 3]

array([1, 2, 3])

In [157]:
v[v == 3]

array([3])

In [158]:
v[v != 3]

array([1, 2, 4, 5])

In [159]:
v

array([1, 2, 3, 4, 5])

In [160]:
v * 2

array([ 2,  4,  6,  8, 10])

In [161]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [162]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [163]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel İşlemler

In [164]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [165]:
v - 1

array([0, 1, 2, 3, 4])

In [166]:
v * 5

array([ 5, 10, 15, 20, 25])

In [167]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [168]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [189]:
#ufunc


In [170]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [171]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [172]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [173]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [174]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [175]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [176]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [177]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [178]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [190]:
np.absolute(np.array([-3]))
# mutlak değer fonk.

array([3])

In [180]:
np.sin(360)

0.9589157234143065

In [181]:
np.cos(180)

-0.5984600690578581

In [182]:
v = np.array([1,2,3])

In [183]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [184]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [185]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [186]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\halil\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\halil\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

In [193]:
#cheatsheet = kopya kağıdı.
#https://web.itu.edu.tr/iguzel/files/Python_Cheat_Sheets.pdf

# İstatistiksel Hesaplamalar

In [191]:
v

array([1, 2, 3])

In [192]:
np.mean(v)

2.0

In [30]:
v.sum()

6

In [31]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [2]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [3]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [4]:
a

array([[5, 1],
       [1, 3]])

In [5]:
b

array([12, 10])

In [6]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])